---
services: 
  - docker

jobs:
  include:
    - stage: Tests API
      if: type = pull_request OR type = push AND branch = master
      script:
        - ./ci/tests.sh
        - ./ci/api/test_api.sh
