---
services: 
  - docker

jobs:
  include:
    - stage: Tests API
      if: type = pull_request AND branch = master
      script:
        - ./ci/tests.sh
    # - stage: Deploy Back
    #   if: type = push AND branch = master
    #   script:
    #     - docker login -u $DOCKERUSERNAME -p $DOCKERPASSWORD
    #     - docker build
    #     - docker push berthieresteban/timemanager_api:latest
    - stage: Deploy Front
      if: type = push AND branch = master
      install:
        - pip install awscli --upgrade --user
      script:
        - cd ./frontend
        - npm install
        - npm run build
        - aws s3 sync ./dist/ s3://timemanager
