---
services: 
  - docker

jobs:
  include:
    - stage: Tests Frontend
      if: type IN (push, pull_request) AND branch = master
      install: 
        - npm install --prefix ./frontend
      script:
        - ./ci/run_api.sh
        - ./ci/run_front.sh
        - npm run test --prefix ./frontend
    - stage: Tests API
      if: type IN (push, pull_request) AND branch = master
      script:
        - ./ci/run_api.sh
        - ./api/test/test_api.sh
    - stage: Deploy Back
      if: type = push AND branch = master
      script:
        - docker login -u $DOCKERUSERNAME -p $DOCKERPASSWORD
        - docker-compose build
        - docker push berthieresteban/timemanager_api:latest
    - stage: Deploy Front
      if: type = push AND branch = master
      addons:
        apt:
          packages:
            - "python3"
            - "python3-pip"
      install:
        - pip3 install awscli --upgrade --user
      script:
        - cd ./frontend
        - npm install
        - npm run build
        - aws s3 sync ./dist/ s3://timemanager --delete
