#
# Docker compose file
# EPITECH 2019 - TimeManager
# Julien Legay x Esteban Berthier x Lucas Lemoigne x Niels Norca
#
version : '3'
services:
    api:
        container_name: berthieresteban/timemanager_api
        image: berthieresteban/timemanager_api
        environment:
            PGUSER: postgres
            PGPASSWORD: postgres
            PGDATABASE: timemanager_dev
            PGPORT: 5432
            PGHOST: db
        ports:
            - "4000:4000"
        depends_on:
            - db
    front:
        image: berthieresteban/timemanager_front
        ports:
            - "8080:8080"
        container_name: berthieresteban/timemanager_front
    db:
        container_name: timemanager_db
        image: postgres:9.6
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        restart: always
        volumes:
            - "dbdata:/var/lib/postgresql/data"
volumes:
    dbdata: